export const ACTIONS = {
    GET_SHOPS: "GET_SHOPS",
  GET_SHOPS_SUCCESS: "GET_SHOPS_SUCCESS",
  GET_SHOPS_FAILURE: "GET_SHOPS_FAILURE",
  GET_SHOP: "GET_SHOP",
  GET_SHOP_SUCCESS: "GET_SHOP_SUCCESS",
  GET_SHOP_FAILURE: "GET_SHOP_FAILURE",
};